// Permission matrix for role-based access control
import { ROLES } from '../constants';

export { ROLES };

export const PERMISSIONS = {
  // Dashboard
  VIEW_CLUB_DASHBOARD: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  VIEW_DEPT_DASHBOARD: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  VIEW_PERSONAL_DASHBOARD: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  // Tasks
  VIEW_ALL_TASKS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  VIEW_DEPT_TASKS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  CREATE_TASK: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  EDIT_ANY_TASK: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  EDIT_DEPT_TASK: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  DELETE_TASK: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  APPROVE_TASK: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  MOVE_TASK: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  // Members
  VIEW_ALL_MEMBERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  VIEW_DEPT_MEMBERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  ADD_MEMBER: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  EDIT_MEMBER: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  DELETE_MEMBER: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  // Finance
  VIEW_FINANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_FINANCE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
  // Documents
  VIEW_DOCUMENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  UPLOAD_DOCUMENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  DELETE_DOCUMENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  // Settings
  VIEW_SETTINGS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_DEPARTMENTS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SYSTEM_AUDIT_LOG: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SYSTEM_BACKUP: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  SYSTEM_STATISTICS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
};

export const can = (user, permission) => {
  if (!user) return false;
  // Hỗ trợ cả userProfile (Firestore) và customClaims
  const role = user.role || user.customClaims?.role;
  if (!role) return false;
  return PERMISSIONS[permission]?.includes(role) || false;
};
